#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using WProject.DataAccess;

namespace WProject.DataAccess	
{
	[Table("active_session")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	public partial class ActiveSession : INotifyPropertyChanging, INotifyPropertyChanged
	{
		private int _id;
		[Column("id", OpenAccessType = OpenAccessType.Int32, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer")]
		[Storage("_id")]
		[System.ComponentModel.DataAnnotations.Required()]
		[System.ComponentModel.DataAnnotations.Key()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private DateTime _createdAt;
		[Column("created_at", OpenAccessType = OpenAccessType.DateTime, Length = 0, Scale = 0, SqlType = "datetime")]
		[Storage("_createdAt")]
		[System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual DateTime CreatedAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if(this._createdAt != value)
				{
					this.OnPropertyChanging("CreatedAt");
					this._createdAt = value;
					this.OnPropertyChanged("CreatedAt");
				}
			}
		}
		
		private string _uid;
		[Column("uid", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 512, Scale = 0, SqlType = "nvarchar")]
		[Storage("_uid")]
		[System.ComponentModel.DataAnnotations.StringLength(512)]
		public virtual string Uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if(this._uid != value)
				{
					this.OnPropertyChanging("Uid");
					this._uid = value;
					this.OnPropertyChanged("Uid");
				}
			}
		}
		
		private int _userId;
		[Column("user_id", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "integer")]
		[Storage("_userId")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int UserId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if(this._userId != value)
				{
					this.OnPropertyChanging("UserId");
					this._userId = value;
					this.OnPropertyChanged("UserId");
				}
			}
		}
		
		private DateTime? _lastHeartBeat;
		[Column("last_heart_beat", OpenAccessType = OpenAccessType.DateTime, IsNullable = true, Length = 0, Scale = 0, SqlType = "timestamp")]
		[Storage("_lastHeartBeat")]
		[System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
		public virtual DateTime? LastHeartBeat
		{
			get
			{
				return this._lastHeartBeat;
			}
			set
			{
				if(this._lastHeartBeat != value)
				{
					this.OnPropertyChanging("LastHeartBeat");
					this._lastHeartBeat = value;
					this.OnPropertyChanged("LastHeartBeat");
				}
			}
		}
		
		private string _ip;
		[Column("ip", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 128, Scale = 0, SqlType = "nvarchar")]
		[Storage("_ip")]
		[System.ComponentModel.DataAnnotations.StringLength(128)]
		public virtual string Ip
		{
			get
			{
				return this._ip;
			}
			set
			{
				if(this._ip != value)
				{
					this.OnPropertyChanging("Ip");
					this._ip = value;
					this.OnPropertyChanged("Ip");
				}
			}
		}
		
		private string _contextId;
		[Column("context_id", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 512, Scale = 0, SqlType = "nvarchar")]
		[Storage("_contextId")]
		[System.ComponentModel.DataAnnotations.StringLength(512)]
		public virtual string ContextId
		{
			get
			{
				return this._contextId;
			}
			set
			{
				if(this._contextId != value)
				{
					this.OnPropertyChanging("ContextId");
					this._contextId = value;
					this.OnPropertyChanged("ContextId");
				}
			}
		}
		
		private string _metadata;
		[Column("metadata", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "text")]
		[Storage("_metadata")]
		public virtual string Metadata
		{
			get
			{
				return this._metadata;
			}
			set
			{
				if(this._metadata != value)
				{
					this.OnPropertyChanging("Metadata");
					this._metadata = value;
					this.OnPropertyChanged("Metadata");
				}
			}
		}
		
		private User _user;
		[ForeignKeyAssociation(ConstraintName = "active_session_user_FK_user_id", SharedFields = "UserId", TargetFields = "Id")]
		[Storage("_user")]
		public virtual User User
		{
			get
			{
				return this._user;
			}
			set
			{
				if(this._user != value)
				{
					this.OnPropertyChanging("User");
					this._user = value;
					this.OnPropertyChanged("User");
				}
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
